name: Build Java project

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Build Gradle
        working-directory: ./dummy
        run: |
          ./gradlew build
          docker build -f src/main/docker/Dockerfile.jvm -t dummy:latest .
          docker images